// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egrofjjisetnvfpbhnwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVncm9mamppc2V0bnZmcGJobndxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM3ODA5NzgsImV4cCI6MjA0OTM1Njk3OH0.nmEQTJLvGwRLalitPg9R8kYcfcvOoWTCaS-_p2eMYQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);